import { ref } from "vue";
import { nanoid } from "nanoid";

import { generateUniqueCoordinates } from "./generateCoordinates";

const townTypes = ["village", "town", "city", "metropolis"];
const townTypeProbabilities = [0.75, 0.15, 0.08, 0.02];

function getRandomTownType() {
  const randomNumber = Math.random();
  let cumulativeProbability = 0;

  for (let i = 0; i < townTypeProbabilities.length; i++) {
    cumulativeProbability += townTypeProbabilities[i];
    if (randomNumber < cumulativeProbability) {
      return townTypes[i];
    }
  }
}

const generateTown = () => {
  const town = ref({
    id: nanoid(),
    name: `${randomNameGenerator()}`,
    type: getRandomTownType(),
    wealth: 0,
    budget: 0,
    tax: Math.random() * 0.1 + 0.05,
    coordinates: generateUniqueCoordinates(),
    goods: [],
    population: [],
  });

  town.value.wealth = generateWealth(town.value.type);
  town.value.budget = generateBudget(town.value.type);

  return town;
};

const generateTowns = (count) => {
  const towns = [];
  for (let i = 0; i < count; i++) {
    towns.push(generateTown());
  }
  return towns;
};

const randomNameGenerator = () => {
  const names = [
    "Baley",
    "Grigo",
    "Porge",
    "Neat",
    "Muhovo",
    "Asperg",
    "Stonel",
    "Ironer",
    "Castlehaven",
    "Kingsbridge",
    "Ravenshire",
    "Silverglen",
    "Stonehaven",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsreach",
    "Dragonvale",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Dragonvale",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Dragonvale",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Dragonvale",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Dragonvale",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
    "Sunwood",
    "Mistvale",
    "Ravenpeak",
    "Elderglen",
    "Silverstone",
    "Kingsreach",
    "Dragonspire",
    "Elverwood",
    "Ironforge",
    "Shadowvale",
    "Moonstone",
    "Suncrest",
    "Misthaven",
    "Ravenstone",
    "Eldershire",
    "Silverthorne",
    "Kingsbridge",
    "Elvenwood",
    "Ironhold",
    "Shadowmere",
    "Mooncrest",
    "Sunhaven",
    "Mistvale",
    "Ravencrest",
    "Elderglen",
    "Silverstone",
    "Kingsglen",
    "Dragonpeak",
    "Elverstone",
    "Ironwood",
    "Shadowglen",
    "Moonvale",
    "Sunstone",
    "Mistwood",
    "Ravenwood",
    "Elderspire",
    "Silverwood",
    "Kingsgate",
    "Dragonvale",
    "Elverstone",
    "Ironwood",
    "Shadowmere",
    "Mooncrest",
  ];
  return names[Math.floor(Math.random() * names.length)];
};

function generateWealth(type) {
  if (type === "village") {
    return Math.random() * 20 + 20;
  } else if (type === "town") {
    return Math.random() * 30 + 30;
  } else if (type === "city") {
    return Math.random() * 40 + 40;
  } else if (type === "metropolis") {
    return Math.random() * 50 + 50;
  } else {
    return console.log("city type is wrong");
  }
}

function generateBudget(type) {
  if (type === "village") {
    return Math.random() * 500 + 500;
  } else if (type === "town") {
    return Math.random() * 1500 + 1500;
  } else if (type === "city") {
    return Math.random() * 6000 + 4000;
  } else if (type === "metropolis") {
    return Math.random() * 15000 + 10000;
  } else {
    return console.log("city type is wrong");
  }
}

export { generateTowns, generateTown };
